Vs30map qgisserver
ucgmsim/mapping pull request #13
Opened 2024-07-25 02:04 UTC by sungeunbae

Revised READMEs to incorporate the changes due to migration out of RCC VM.
QGIS server is now running on Hypocentre and the static portion of Vs30 map remains to be hosted on ucquakecore2p.

2024-07-25 23:09 UTC, joelridden approved these changes

2024-07-28 19:33 UTC, claudio525 approved these changes

2024-07-28 22:15 UTC, lispandfound requested changes

2024-07-28 22:15 UTC, lispandfound commented on mapbox/vs30/README.md
> +7. Restart qgis server at Hypoctnre.
```suggestion
7. Restart qgis server at Hypocentre.
```

2024-07-28 22:15 UTC, lispandfound commented on mapbox/vs30/README.md
> +QGIS is a little fiddly here. To make sure the min and max are updated, try some random values for min and max (eg.0 and 1000), select User defined, and click apply. Then change it to Min/max and app
```suggestion
QGIS is a little fiddly here. To make sure the min and max are updated, try some random values for min and max (e.g. 0 and 1000), select User defined, and click apply. Then change it to Min/max and apply again. This should find a new Min and Max values.
```

2024-07-29 21:16 UTC, lispandfound approved these changes

2024-07-29 21:36 UTC, claudio525 approved these changes

2024-07-31 05:42 UTC, AndrewRidden-Harper approved these changes

2024-08-02 00:03 UTC, merged